apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pomy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pomy
    app.kubernetes.io/part-of: tkrw-pr714-0075-0036-app
  name: devfile-sample-pomy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pomy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pomy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0036-tenant/tkrw-pr714-0075-0036-app/devfile-sample-pomy@sha256:07b40d7708004fba2cba9c8bc38ad96e8b8103358f069751f537d701bf14704c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
